default: &default
  adapter: postgresql
  pool: 10
  timeout: 5000

development:
  <<: *default
  database: be_live_development

test: &test
  <<: *default
  database: be_live_test

production:
  <<: *default
  pool: <%= ENV['DB_POOL'] || ENV['MAX_THREADS'] || 5 %>
  database: be_live
